(function() { //Sonobi - Morpheus version:3.7.10
'use strict';var v="function"==typeof Object.defineProperties?Object.defineProperty:function(h,e,l){if(l.get||l.set)throw new TypeError("ES3 does not support getters and setters.");h!=Array.prototype&&h!=Object.prototype&&(h[e]=l.value)},w="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function D(){D=function(){};w.Symbol||(w.Symbol=ma)}var na=0;function ma(h){return"jscomp_symbol_"+(h||"")+na++}
function E(){D();var h=w.Symbol.iterator;h||(h=w.Symbol.iterator=w.Symbol("iterator"));"function"!=typeof Array.prototype[h]&&v(Array.prototype,h,{configurable:!0,writable:!0,value:function(){return N(this)}});E=function(){}}function N(h){var e=0;return oa(function(){return e<h.length?{done:!1,value:h[e++]}:{done:!0}})}function oa(h){E();h={next:h};h[w.Symbol.iterator]=function(){return this};return h}function V(h){E();D();E();var e=h[Symbol.iterator];return e?e.call(h):N(h)}
function pa(h,e){function l(){}l.prototype=e.prototype;h.prototype=new l;h.prototype.constructor=h;for(var n in e)if(Object.defineProperties){var m=Object.getOwnPropertyDescriptor(e,n);m&&Object.defineProperty(h,n,m)}else h[n]=e[n]}function W(h,e){if(e){var l=w;h=h.split(".");for(var n=0;n<h.length-1;n++){var m=h[n];m in l||(l[m]={});l=l[m]}h=h[h.length-1];n=l[h];e=e(n);e!=n&&null!=e&&v(l,h,{configurable:!0,writable:!0,value:e})}}
W("Promise",function(h){function e(f){this.b=0;this.l=void 0;this.a=[];var e=this.h();try{f(e.resolve,e.reject)}catch(x){e.reject(x)}}function l(){this.a=null}if(h)return h;l.prototype.b=function(f){this.a||(this.a=[],this.h());this.a.push(f)};l.prototype.h=function(){var f=this;this.f(function(){f.l()})};var n=w.setTimeout;l.prototype.f=function(f){n(f,0)};l.prototype.l=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var e=0;e<f.length;++e){var h=f[e];delete f[e];try{h()}catch(C){this.i(C)}}}this.a=
null};l.prototype.i=function(f){this.f(function(){throw f;})};e.prototype.h=function(){function f(f){return function(t){h||(h=!0,f.call(e,t))}}var e=this,h=!1;return{resolve:f(this.Ma),reject:f(this.i)}};e.prototype.Ma=function(f){if(f===this)this.i(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof e)this.Na(f);else{var h;a:switch(typeof f){case "object":h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.Ga(f):this.v(f)}};e.prototype.Ga=function(f){var e=void 0;
try{e=f.then}catch(x){this.i(x);return}"function"==typeof e?this.oa(e,f):this.v(f)};e.prototype.i=function(f){this.R(2,f)};e.prototype.v=function(f){this.R(1,f)};e.prototype.R=function(f,e){if(0!=this.b)throw Error("Cannot settle("+f+", "+e|"): Promise already settled in state"+this.b);this.b=f;this.l=e;this.Fa()};e.prototype.Fa=function(){if(this.a){for(var f=this.a,e=0;e<f.length;++e)f[e].call(),f[e]=null;this.a=null}};var m=new l;e.prototype.Na=function(e){var f=this.h();e.f(f.resolve,f.reject)};
e.prototype.oa=function(e,h){var f=this.h();try{e.call(h,f.resolve,f.reject)}catch(C){f.reject(C)}};e.prototype.then=function(f,h){function l(e,f){return"function"==typeof e?function(f){try{n(e(f))}catch(z){m(z)}}:f}var n,m,t=new e(function(e,f){n=e;m=f});this.f(l(f,n),l(h,m));return t};e.prototype.catch=function(e){return this.then(void 0,e)};e.prototype.f=function(e,h){function f(){switch(l.b){case 1:e(l.l);break;case 2:h(l.l);break;default:throw Error("Unexpected state: "+l.b);}}var l=this;this.a?
this.a.push(function(){m.b(f)}):m.b(f)};e.resolve=function(f){return f instanceof e?f:new e(function(e){e(f)})};e.reject=function(f){return new e(function(e,h){h(f)})};e.b=function(f){return new e(function(h,l){for(var n=V(f),m=n.next();!m.done;m=n.next())e.resolve(m.value).f(h,l)})};e.a=function(f){var h=V(f),l=h.next();return l.done?e.resolve([]):new e(function(f,n){function m(e){return function(h){t[e]=h;x--;x||f(t)}}var t=[],x=0;do t.push(void 0),x++,e.resolve(l.value).f(m(t.length-1),n),l=h.next();
while(!l.done)})};e.$jscomp$new$AsyncExecutor=function(){return new l};return e});W("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});W("Array.from",function(h){return h?h:function(e,h,n){E();h=h?h:function(e){return e};var l=[],f=e[Symbol.iterator];if("function"==typeof f)for(e=f.call(e);!(f=e.next()).done;)l.push(h.call(n,f.value));else for(var f=e.length,t=0;t<f;t++)l.push(h.call(n,e[t]));return l}});
W("Object.assign",function(h){return h?h:function(e,h){for(var l=1;l<arguments.length;l++){var m=arguments[l];if(m)for(var f in m)Object.prototype.hasOwnProperty.call(m,f)&&(e[f]=m[f])}return e}});W("Array.prototype.find",function(h){return h?h:function(e,h){a:{var l=this;l instanceof String&&(l=String(l));for(var m=l.length,f=0;f<m;f++){var t=l[f];if(e.call(h,t,f,l)){e=t;break a}}e=void 0}return e}});
(function(h){function e(){var a=k.sbi_morpheus||{registration:{},register:function(){},enableReactiveSizes:function(){},callOperator:function(){},initialized:!1,initialize:function(){for(var b=a.cmd;0<b.length;)try{b.shift()()}catch(c){}a.initialized=!0},cmd:function(){var a=[],c=a.push;a.push=function(b){for(var d=[],q=0;q<arguments.length;++q)d[q-0]=arguments[q];return k.sbi_morpheus.initialized?d.reduce(function(a,b){try{b()}catch(p){}a++;return a},0):c.apply(a,d)};return a}()};return a}function l(a){this.cb=
new n(a);this.P=new J(a);this.H=new O(a)}function n(a){this.a=a.analyticsSettings;this.P=new J(a)}function m(a,b){this.c=a;this.b=b;this.caller=new A;this.a=[]}function f(a,b){this.c=a;this.b={};this.L=b;this.a={}}function t(a,b){var c=a.Wa({name:b});if(c)return{Ja:c,exec:function(a){return r.Ca(k,a.value)}};if(c=a.Wa({name:""+b+"_cookie_key"}))return{Ja:c,exec:function(a){return r.lb(a.value)}}}function x(a){return{Ja:{name:"vp"},exec:function(){return(r.ia(a.H.$())||"desktop").toLowerCase()}}}function C(a){var b=
["hfa","cdf","ant"].map(function(b){return t(a,b)}).filter(function(a){return a});b.push(x(a));return b.reduce(function(a,b){var c=b.Ja;b=b.exec;var d="";"function"===typeof b&&(d=b(c));if(!d)return a;if("object"===typeof d||Array.isArray(d))d=JSON.stringify(d);return a+"&"+c.name.replace("_cookie_key","")+"="+encodeURIComponent(d)},"")}function I(a,b,c,d,g,q,qa){this.da=r.Ba();this.l=d;this.S=g;this.X=0;this.T=c;this.ea=b;this.b="";this.Z=a;this.i={};this.pa="";this.f=10;this.a=-1;this.Y=1;this.h=
{};this.W=qa;this.V=0;this.v="display";"function"===typeof q.O&&q.O(this.ha(1))}function X(a){this.name=a.name;this.ua=a.ua;this.Ka=a.Ka;this.request=a.request;this.parse=a.parse;this.done=Function;this.caller=new A;this.qa={};this.c={};this.b=Promise.resolve({});this.a=!1}function F(a,b){if(!b)throw Error("Provide an adapter name in your AdapterSettingsConfigInterface constructor.");this.f=a.adapterSettings;this.H=new O(a);a=this.f;for(var c={},d=0;d<a.length;d++)c[a[d].name]=a[d];this.b=c;this.B=
b;this.a=this.b[b];this.v=Y;this.l=Z}function O(a){this.a=a.platformSettings;this.P=new J(a)}function J(a){this.a=a.globalSettings}function z(a,b,c,d){this.c=a;this.va=b;this.a={};this.i=c;this.L=d;var g=this;this.Aa=function(a){if("object"!==typeof a)return g.a;a.aa=!1;return Object.keys(g.a).reduce(function(b,c){var d=g.a[c],q;for(q in a)if(d[q]!==a[q])return b;b[c]=d;return b},{})};this.ga=function(a){if("object"===typeof a)return a.aa=!1,g.a[Object.keys(g.a).find(function(b){b=g.a[b];for(var c in a)if(b[c]!==
a[c])return!1;return!0})]};this.h=function(){};this.b=new u(this.c,this);k.sbi_km.API.render=function(){var a=arguments,b=Date.now(),d=Object.assign({},c.ta),p=d[Object.keys(d||{}).find(function(b){b=d[b];return b.id===a[1]&&!b.ba})];if(p){var e=g.a[p.m];e&&(e.wb[p.id]=b,g.b.Ma(e,arguments[0],p.fa,p.size,arguments[2],arguments[3]).then(function(a){g.c.log("sbi",200019,[p.g,p.A]);p.response=6;p.ba=!0;g.L.O(p.ha(3));a.Oa={}},function(a){try{g.c.log("sbi",200021,[p.g,p.A])}catch(G){g.c.log("sbi",200040,
[G])}a.Oa={}}))}};this.b.once("initialized",function(a,b){g.c.log("sbi",200003,[a]);g.f(a);"function"===typeof b&&b();g.b.w("slotsDefined",function(a){g.c.log("sbi",200027,[a]);g.f(a)})});this.b.w("slotsDestroyed",function(a){a.forEach(function(a){var b=g.b.h(a);a=g.b.R(a);for(var c in g.a)g.a[c].u==b&&g.a[c].m==a&&(g.a[c].aa=!0,g.c.log("sbi",200028,[g.a[c]]))},this)});this.b.w("getSlots",function(a,b){"object"!==typeof a?b(g.a):(a.aa=!1,b(Object.keys(g.a).reduce(function(b,c){var d=g.a[c],q;for(q in a)if(d[q]!==
a[q])return b;b[c]=d;return b},{})))});this.b.w("findSlot",function(a,b){"object"!==typeof a?b({}):(a.aa=!1,b(g.a[Object.keys(g.a).find(function(b){b=g.a[b];for(var c in a)if(b[c]!==a[c])return!1;return!0})]))});this.b.w("slotsRequestingRender",function(a){var b=g.l(a.C);g.h(b,a.done)});this.b.w("newPageViewRequested",function(){g.b.oa()});this.b.w("log",function(a){g.c.log.apply(g.c,Array.isArray(a)?a:[a])})}function u(a,b){var c;this.a={};c=this;c.G=!1;c.Ra=Function;c.wa=Function;c.Xa={};c.j={};
c.c=a;c.ma=[];c.Aa=b.Aa;c.ga=b.ga;k.googletag=k.googletag||{};k.googletag.cmd=k.googletag.cmd||[];if(k.googletag.pubadsReady)a.log("sbi",200039);else{a=null!=k.googletag.cmd.length?"unshift":"push";var d=!1,g=function(){d||(d=!0,c.Xa=k.googletag,c.j=c.Xa.pubads(),c.j.disableInitialLoad(),c.tb(),c.Bb())};k.googletag.cmd[a](g);if(!1!==P(b.va,"globalSettings.osEnabled")&&"u"===a[0]){var e=k.googletag.cmd.splice;k.googletag.cmd[a]=function(a){e.apply(k.googletag.cmd,[1,0,a]);return this.length};k.googletag.cmd.splice=
function(){var a=e.apply(k.googletag.cmd,arguments);e.apply(k.googletag.cmd,[0,0,g]);return a}}c.ca={Ub:!1,Sa:!1,Ua:!1,hb:!1};c.sa={}}return c}function M(){this.a={}}function H(a){this.caller=new A;this.va=a;this.a=!1;this.navigationStart=k.performance.timing.navigationStart}function A(a){this.timeout=void 0===a?3E4:a}function Q(a){var b=!1;return function(c){for(var d=[],g=0;g<arguments.length;++g)d[g-0]=arguments[g];if(!b){b=!0;try{a.apply(void 0,d)}catch(q){}}}}function aa(a){a=void 0===a?[]:a;
if(!Array.isArray(a))return[];a=Array.from(a);for(var b=a.length;b;b--){var c=Math.floor(Math.random()*b),d=V([a[c],a[b-1]]);a[b-1]=d.next().value;a[c]=d.next().value}return a}function ra(a){return parseInt(a,10)}function P(a,b){var c;if(b&&"string"===typeof b){if(-1!==b.indexOf(".")){b=b.split(".");for(var d=!1,g=0;g<b.length;g++){if("object"!==typeof a){d=!0;break}a=P(a,b[g])}d||(c=a);return c}d="get"+b[0].toUpperCase()+b.slice(1);b=a&&"function"===typeof a[d]?d:b;a&&(a.hasOwnProperty(b)||"function"===
typeof a[b])&&(c="function"===typeof a[b]?a[b]():a[b]);return c}}function ba(a){return a?'<script type="text/javascript" src="'+a+'">\x3c/script>':""}function ca(a,b){if(!a)return"";b=b.split("x");return'<iframe id="'+B()+'" width="'+b[0]+'" height="'+b[1]+'" marginwidth="0" marginheight="0" style="border:0" frameborder="0" src="'+a+'" border="0" scrolling="no" vspace="0" hspace="0"></iframe>'}function da(a){return a?'<div style="position:absolute;left:0px;top:0px;visibility:hidden;">'+('<img src="'+
a+'"></div>'):""}function ea(a,b){var c=[];a.forEach(function(a){-1!==b.indexOf(a)&&c.push(a)});return c}function fa(){return[k.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,k.innerHeight||document.documentElement.clientHeight||document.body.clientHeight]}function ga(a,b){a=Math.round(a);for(var c=0;c<b.length;c++){var d="lt"in b[c]&&a<b[c].lt||!("lt"in b[c]);!("ge"in b[c]&&a>=b[c].ge)&&"ge"in b[c]||!d||("set"in b[c]?a=b[c].set:"round"in b[c]&&(a=Math.floor(a)-Math.floor(a)%
b[c].round))}return a}function ha(a,b,c){Object.keys(b).forEach(function(d){a=a.replace(c+d+c,b[d])});return a}function B(){return sa()+Math.random().toString(16).substr(2)}function ta(a){return a?a.replace(/^\?/,"").split("&").reduce(function(a,c){var b=V(c.split("="));c=b.next().value;b=b.next().value;/\[\]$/.test(c)?(c=c.replace("[]",""),a[c]=a[c]||[],a[c].push(b)):a[c]=b||"";return a},{}):{}}function ua(a){return Object.keys(a).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+
"[]="+a}).join("&"):b+"="+a[b]}).join("&")}function va(a){var b=document.createElement("a");b.href=decodeURIComponent(a);return{protocol:(b.protocol||"").replace(/:$/,""),hostname:b.hostname,port:+b.port,pathname:b.pathname,search:ta(b.search||""),hash:(b.hash||"").replace(/^#/,""),host:b.host}}function wa(a){return(a.protocol||"http")+"://"+(a.host||a.hostname+(a.port?":"+a.port:""))+(a.pathname||"")+(a.search?"?"+ua(a.search||""):"")+(a.hash?"#"+a.hash:"")}function Y(a,b,c){a=r.Ca(a,void 0===c?
"dimensions.platforms":c)||[];return"*"===b||0===a.length||-1<a.indexOf("*")?!0:-1<a.indexOf(b)}function Z(a,b){var c=k.location.href;a=r.Ca(a,void 0===b?"dimensions.domains":b)||[];if(0===a.length||-1<a.indexOf("*"))return!0;if("string"===typeof a)return(new RegExp(a)).test(c);for(b=0;b<a.length;b++)if((new RegExp(a[b])).test(c))return!0;return!1}function xa(a,b,c,d,g,e){return{xb:function(q,f){k.sbi_morpheus.initialized||k.sbi_morpheus.initialize();if(Object.keys(q).length){var p=B();a.yb(q,b,c,
p,Q(function(b){var c=Object.keys(b).map(function(a){return b[a]});c.length?(d.Ab(a.kb(c,g.P.ja("priceRules")||[])),c=c.map(function(a){return a.clone()}),c.length&&(c=c.map(function(a){a.m=q[a.m].m;return a}),e.ra(c),f())):f()}))}}}}var k=window;(function(){(function(a){0=="performance"in a&&(a.performance={});Date.now=Date.now||function(){return(new Date).getTime()};if(0=="now"in a.performance){var b=Date.now();a.performance.timing&&a.performance.timing.navigationStart?b=a.performance.timing.navigationStart:
a.performance.timing={navigationStart:Date.now()};a.performance.now=function(){return Date.now()-b}}})(k);Object.assign||Object.defineProperty(Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:function(a,b){if(void 0===a||null===a)throw new TypeError("Cannot convert first argument to object");for(var c=Object(a),d=1;d<arguments.length;d++){var g=arguments[d];if(void 0!==g&&null!==g)for(var e=Object.keys(Object(g)),f=0,h=e.length;f<h;f++){var p=e[f],k=Object.getOwnPropertyDescriptor(g,
p);k&&k.enumerable&&(c[p]=g[p])}}return c}});k.Promise||(k.Promise=function(){function a(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)}function b(){}function c(a,b){return function(){a.apply(b,arguments)}}function d(a){if("object"!==typeof this)throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.F=0;this.Qa=!1;this.I=void 0;this.U=[];k(a,this)}function g(a,b){for(;3===a.F;)a=
a.I;0===a.F?a.U.push(b):(a.Qa=!0,G(function(){var c=1===a.F?b.rb:b.sb;if(null===c)(1===a.F?e:f)(b.Ha,a.I);else{var d;try{d=c(a.I)}catch(ya){f(b.Ha,ya);return}e(b.Ha,d)}}))}function e(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var d=b.then;if(b instanceof Promise){a.F=3;a.I=b;h(a);return}if("function"===typeof d){k(c(d,b),a);return}}a.F=1;a.I=b;h(a)}catch(R){f(a,R)}}function f(a,b){a.F=2;a.I=b;h(a)}function h(b){2===
b.F&&0===b.U.length&&G(function(){b.Qa||a(b.I)});for(var c=0,d=b.U.length;c<d;c++)g(b,b.U[c]);b.U=null}function p(a,b,c){this.rb="function"===typeof a?a:null;this.sb="function"===typeof b?b:null;this.Ha=c}function k(a,b){var c=!1;try{a(function(a){c||(c=!0,e(b,a))},function(a){c||(c=!0,f(b,a))})}catch(R){c||(c=!0,f(b,R))}}var l=setTimeout,G="function"===typeof setImmediate&&setImmediate||function(a){l(a,0)};d.prototype["catch"]=function(a){return this.then(null,a)};d.prototype.then=function(a,c){var d=
new this.constructor(b);g(this,new p(a,c,d));return d};d.all=function(a){var b=Array.prototype.slice.call(a);return new d(function(a,c){function d(e,f){try{if(f&&("object"===typeof f||"function"===typeof f)){var p=f.then;if("function"===typeof p){p.call(f,function(a){d(e,a)},c);return}}b[e]=f;--g||a(b)}catch(za){c(za)}}if(!b.length)return a([]);for(var g=b.length,e=0;e<b.length;e++)d(e,b[e])})};d.resolve=function(a){return a&&"object"===typeof a&&a.constructor===d?a:new d(function(b){b(a)})};d.reject=
function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,c){for(var d=0,g=a.length;d<g;d++)a[d].then(b,c)})};d._setImmediateFn=function(a){G=a};d._setUnhandledRejectionFn=function(b){a=b};return d}())})();var sa=function(){var a=0;return function(){a++;return a}}(),ia={highestCPMWins:function(a,b){if(0==a.length)return null;for(var c={g:0},d=0;d<a.length;d++)c.g>=a[d].g?b.log("sbi",200017,[a[d].g,a[d].A]):c=a[d];return c.g?c:null},sonobiDealWinsOverHighestCPM:function(a,
b){if(0===a.length)return null;for(var c={g:0},d=0;d<a.length;d++)if(10<=a[d].N)a[d].g>c.g&&(b.log("sbi",200017,[c.g,c.A]),c=a[d]);else{if("sonobi"===a[d].A&&a[d].J){c=a[d];a.forEach(function(g){g!==c&&b.log("sbi",200017,[a[d].g,a[d].A])});break}c.g>=a[d].g?b.log("sbi",200017,[a[d].g,a[d].A]):c=a[d]}return c.g||c.J?c:null},lowestDealPriorityWinsOverHighestCPM:function(a,b){if(0===a.length)return null;a.sort(function(a,b){return a.N-b.N});var c=a[0].N,d=a.filter(function(a){return a.N===c});a={g:0};
for(var d=V(d),g=d.next();!g.done;g=d.next())g=g.value,a.g>=g.g?b.log("sbi",200017,[g.g,g.A]):a=g;return a.g||a.J?a:null}},r={Ba:B,Lb:function(a){var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;return b.test(a)?a.replace(b,function(a){var b={"\b":"\\b"," ":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"}[a];return("string"==typeof b?b:"\\u")+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}):a},Rb:function(a){if(a){var b;
try{b=a.contentWindow?a.contentWindow.document:a.contentDocument.document?a.contentDocument.document:a.contentDocument}catch(c){return}return b}},Qb:function(){var a=document.createElement("iframe");a.id=B();a.height=0;a.width=0;a.hspace="0";a.vspace="0";a.marginWidth="0";a.marginHeight="0";a.style.border="0";a.frameBorder="0";a.border="0px";a.scrolling="no";a.src="about:blank";a.style.display="none";return a},bc:ha,Wb:function(){return"Worker"in k&&"Blob"in k},Zb:function(a,b){for(var c=0,d=a.length>
b.length?b.length:a.length,g=a.length<b.length?b.length:a.length,e=0;e<d;e++)a[e]==b[e]&&c++;return c/g},Cb:ia,Db:ga,Sb:fa,Mb:ea,Pb:function(a){return Object.keys(a).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+"[]="+a}).join("&"):b+"="+a[b]}).join("&")},jb:function(a){try{var b=new RegExp(a,"i"),c=k.performance.getEntriesByType("resource").filter(function(a){return b.test(a.name)});return c.length&&c[0]?Math.max(c[0].duration||0,0):null}catch(d){return null}},Ea:function(a){return void 0!==
{sizes:1,ac:1,timeout:1}[a]},ia:function(a){var b=k.innerWidth,c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c].viewport.lt||Number.MAX_SAFE_INTEGER;if(b>=(a[c].viewport.ge||0)&&b<d)return c}},mb:function(a,b){return a.reduce(function(a,d){(a[d[b]]=a[d[b]]||[]).push(d);return a},{})},Kb:da,Ib:ca,Jb:ba,fb:function(a,b,c){switch(void 0===b?"SCRIPT":b){case "SCRIPT":return ba(a);case "IFRAME":return ca(a,void 0===c?"1x1":c);case "TRACK":return da(a);case "SCRIPT_BLOCK":return a?'<script type="text/javascript">'+
a+"\x3c/script>":""}return""},Ca:P,Hb:function(a){var b=/^\d{1,4}x\d{1,4}$/;return"string"===typeof a&&b.test(a)?a.split("x").map(ra):a},qb:function(a,b){var c={},d;for(d in a)-1===b.indexOf(d)&&(c[d]=a[d]);return c},lb:function(a){try{return"string"!==typeof a?void 0:k.document.cookie.split("; ").reduce(function(a,c){c=c.split("=");c=V(c);for(var b=c.next().value,g,e=[];!(g=c.next()).done;)e.push(g.value);a[b]=e.join("=");return a},{})[a]}catch(b){}},Eb:aa,zb:function(a){void 0!==k.performance&&
("function"===typeof k.performance.setResourceTimingBufferSize?k.performance.setResourceTimingBufferSize(a):console.log("... Performance.setResourceTimingBufferSize() = NOT supported"))},once:Q};A.prototype.ob=function(a){var b,c;b=void 0===b?"sbi_"+B():b;c=void 0===c?{}:c;var d=this;a=a.replace("%%callback%%",b);return new Promise(function(g){var e=setTimeout(g,d.timeout,c),f,h=Q(function(a){clearTimeout(f);clearTimeout(e);g(a)});k[b]=h;d.a("script",{src:a}).then(function(){f=setTimeout(function(){h(c)},
500)})})};A.prototype.b=function(a,b){var c={method:"POST"},c=void 0===c?{}:c;return new Promise(function(d,g){function e(){4===f.readyState&&d(f.responseText)}var f,h=c.method||(b?"POST":"GET"),p=k.XDomainRequest&&(!k.XMLHttpRequest||void 0===(new k.XMLHttpRequest).responseType);p?(f=new k.XDomainRequest,f.onload=function(){d(f.responseText)},f.onerror=function(){g("xhr on error")},f.ontimeout=function(){g("xhr timeout")},f.onprogress=function(){}):(f=new k.XMLHttpRequest,f.onreadystatechange=e);
if("GET"===h&&b){var l=va(a);Object.assign(l.search,b);a=wa(l)}f.open(h,a);p||(c.withCredentials&&(f.withCredentials=!0),c.$b&&f.setRequestHeader("X-Requested-With","XMLHttpRequest"),f.setRequestHeader("Content-Type",c.contentType||"text/plain"));f.send("POST"===h&&b)})};A.prototype.a=function(a,b){return new Promise(function(c,d){var g;if("image"===a)g=Object.assign(new Image,b);else if("script"===a||" iframe"===a)g=k.document.createElement(a),Object.keys(b||{}).forEach(function(a){g[a]=b[a]}),k.document.head.appendChild(g);
else return d();g.addEventListener?g.addEventListener("load",function(){c()}):g.readyState?g.onreadystatechange=function(){3===g.readyState&&c()}:d()})};A.prototype.Ta=function(a){var b=a.pb,c=a.url,d=a.type,g=a.gb,e=this;return new Promise(function(a,f){if(!g)switch(d){case "image":return e.a("image",{src:c}).then(function(b){return a(b)},function(a){return f(a)});case "js":return e.a("script",{type:"text/javascript",async:!0,src:c}).then(function(b){return a(b)},function(a){return f(a)});case "iframe":return e.a("iframe",
{src:c,style:{width:0,height:0,border:0}}).then(function(b){return a(b)},function(a){return f(a)});default:return Promise.reject({error:"No Valid Type Specified",value:d}).then(function(b){return a(b)},function(a){return f(a)})}setTimeout(function(){e.Ta({pb:b,url:c,type:d,gb:0}).then(function(b){return a(b)},function(a){return f(a)})},g)})};var S=[];H.prototype.log=function(a,b,c,d){d=null!=d?d-this.navigationStart:0+k.performance.now();a={dateTime:d,time:d-0,id:b,service:a};a.Za=c||[];S.push(a);
this.a&&"logData"in k.sbi_km&&(c=k.sbi_km.logData,this.f(c[a.id].service,a.time,c[a.id].template,a.Za))};H.prototype.b=function(){S.sort(function(a,b){return a.time-b.time});return S};H.prototype.f=function(a,b,c,d){var g=[a,b];a=c.apply(c,d);Array.isArray(a)?a.forEach(function(a){return g.push(a)}):g.push(a);k.console.log.apply(console,g)};H.prototype.h=function(){var a=this;this.a=!0;this.caller.a("script",{src:this.va.url+"/morpheus_console.js"}).then(function(){var b=k.sbi_km.logData;a.b().forEach(function(c){a.f(b[c.id].service,
c.time,b[c.id].template,c.Za)})})};M.prototype.b=function(a){if(a in this.a){var b=Array.from(arguments);b.shift();this.a[a].w.forEach(function(a){return a.apply(a,b)});this.a[a].once.forEach(function(a){return a.apply(a,b)});this.a[a].once=[]}};M.prototype.once=function(a,b){this.a[a]=this.a[a]||{w:[],once:[]};this.a[a].once.push(b)};M.prototype.w=function(a,b){this.a[a]=this.a[a]||{w:[],once:[]};this.a[a].w.push(b)};pa(u,M);u.prototype.Ma=function(a,b,c,d,g,e){var f=this,h=this,p=a.u;return new Promise(function(q,
l){var K=a;h.c.log("sbi",200032,[K]);a=f.f(a.u);a.rendering=!0;var L=c;g&&Object.keys(g).forEach(function(a){Array.isArray(g[a])||(g[a]=[g[a]]);L=L.replace("%%"+a+"%%",g[a].join(","))});d=d.split("x");d={M:parseInt(d[0],10),K:parseInt(d[1],10)};if(f.Fa(a,d.M,d.K))if(e)l=k.document.getElementById(p).getElementsByTagName("div"),l=Array.from(l).filter(function(a){return-1<a.id.indexOf("google_ads_iframe")}),l.forEach(function(a){var c=a.childNodes[0];c.width=d.M;c.height=d.K;a.style.width=d.M+"px";a.style.height=
d.K+"px";b.postMessage({creative:L,message:"SBI_RENDER"},"*")});else{if(b.inDapIF)try{k.document.getElementsByName(b.frameElement.name)[0].width=d.M,k.document.getElementsByName(b.frameElement.name)[0].height=d.K}catch(Ba){h.c.log("sbi",200012)}b.document.write(L)}else l(K);h.c.log("sbi",200033,[K]);q(K)})};u.prototype.l=function(a){var b=a.getTargetingMap(),c=Object.keys(b),d=c.filter(function(a){return"sbi"!==a.substr(0,3)});if(c.length!==d.length)for(a.clearTargeting(),c=V(d),d=c.next();!d.done;d=
c.next())d=d.value,a.setTargeting(d,b[d])};u.prototype.f=function(a){var b=this;return this.i().find(function(c){return b.h(c)==a})||null};u.prototype.h=function(a){return a&&"getSlotElementId"in a?a.getSlotElementId():null};u.prototype.i=function(){return this.j.getSlots()};u.prototype.R=function(a){return a.getAdUnitPath()};u.prototype.Fa=function(a,b,c){var d=!1;this.ka(a).forEach(function(a){d=d||a.M==b&&a.K==c});return d};u.prototype.v=function(a){return this.ka(a).map(function(a){return a.M+
"x"+a.K})};u.prototype.ka=function(a){a=a.getSizes.apply(a,fa());a=Array.isArray(a)?a:[];return a.filter(function(a){return"function"===typeof a.getWidth}).map(function(a){return{M:a.getWidth(),K:a.getHeight()}})};u.prototype.Na=function(a,b){a=this.f(a);if(null!=a)for(var c in b)a.setTargeting(c,b[c])};u.prototype.Bb=function(){var a=this,b=k.googletag.debug_log.log;k.googletag.debug_log.log=function(){var c=b.apply(k.googletag.debug_log,arguments);a.b("log",["dfp",c.getMessage().getMessageId()+
1E5,c.getMessage().getMessageArgs(),c.getTimestamp().getTime()])}.bind(k.googletag.debug_log)};u.prototype.oa=function(){this.j.updateCorrelator()};u.prototype.tb=function(){var a=this,b=k.googletag.defineSlot;k.googletag.defineSlot=k.googletag.defineUnit=function(){"/"!=arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var c=b.apply(this,arguments),d=c.defineSizeMapping;c.defineSizeMapping=function(a){d.call(this,a);return this};var g=c.getAdUnitPath;c.getAdUnitPath=function(a){a=g.call(this,
a);return("/"!=a.charAt(0)?"/":"")+a};a.G&&a.b("slotsDefined",[c]);return c};var c=k.googletag.defineOutOfPageSlot;k.googletag.defineOutOfPageSlot=function(){"/"!=arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var b=c.apply(this,arguments),d=b.defineSizeMapping;b.defineSizeMapping=function(a){d.call(this,a);return this};var g=b.getAdUnitPath;b.getAdUnitPath=function(a){a=g.call(this,a);return("/"!=a.charAt(0)?"/":"")+a};b.isOutOfPage=!0;a.G&&a.b("slotsDefined",[b]);return b};var d=k.googletag.destroySlots;
k.googletag.destroySlots=function(){var b=arguments.length?arguments[0]:a.j.getSlots();a.b("slotsDestroyed",b);return d.apply(this,arguments)};this.wa=this.j.refresh;this.j.refresh=function(){var b=Array.from(arguments),c={};0<b.length&&Array.isArray(b[0])?0==b[0].length?c.C=[]:(c.C=[],b[0].forEach(function(b){b&&"object"===typeof b&&"function"===typeof b.getSizes?c.C.push(b):a.c.log("sbi",200036,[b])})):c.C=a.i();c.done=function(){a.c.log("sbi",200029,[c.C]);a.wa.apply(a.j,b)};c.C.forEach(function(b){a.l(b)});
a.b("slotsRequestingRender",c)};this.Ra=k.googletag.display;k.googletag.display=function(){var b=!1;if(a.G){var c=Array.from(arguments),d=a.ga({u:c[0]});if(!d||d&&!d.xa)a.Ra.apply(k.googletag,c),d&&(d.xa=!0),b=!0;if(!a.ca.Sa)if(a.ca.Ua){if(d&&d.xa){var g=a.Aa({za:!1}),e=B();a.sa[e]={};if(0<Object.keys(g).length){Object.keys(g).forEach(function(a){g[a].za=!0});a.sa[e]=g;var c=Object.keys(g).map(function(b){return a.f(g[b].u)}),f={};f.C=c;f.done=function(){var b=a.sa[e],c=Object.keys(b).map(function(c){return a.f(b[c].u)});
a.c.log("sbi",200029,[f.C]);a.wa.apply(a.j,[c,{changeCorrelator:!1}])};f.C.forEach(function(b){a.l(b)});a.b("slotsRequestingRender",f)}}}else if(0<c.length){if(d=a.ga({u:c[0]}))d.za=!0;if(c=a.f(c[0]))a.c.log("sbi",200030,[c]),a.j.refresh([c],{changeCorrelator:!1})}}else a.c.log("sbi",200035,[arguments[0]]),a.ma.push(arguments[0]);return b};var g=this.j.addEventListener;this.j.addEventListener=function(){var b=Array.from(arguments),c=b[1];"slotRenderEnded"==b[0]&&(b[1]=function(){var a=Array.from(arguments);
if(!a[0].isEmpty&&a[0].slot.hasOwnProperty("rendering")){var b=a[0].slot.getTargeting("sbi_size");0<b.length&&(b=b[0].split("x"),b=b.map(function(a){return parseInt(a,10)}),a[0].size=b);delete a[0].slot.rendering}c.apply(c,a)});return g.apply(a.j,b)};var e=k.googletag.enableServices;k.googletag.enableServices=function(){var b=this,c=arguments;a.c.log("sbi",200031);a.G||(a.G=!0,a.b("initialized",a.i(),function(){e.apply(b,c);a.c.log("sbi",200034,[a.ma.toString()]);a.ma.forEach(function(a){return k.googletag.display(a)});
a.ma=[]}))};var f=this.j.enableSingleRequest;this.j.enableSingleRequest=function(){a.G||(a.ca.Ua=!0);f.apply(this,arguments)};this.j.disableInitialLoad=function(){a.G||(a.ca.Sa=!0)};var h=this.j.enableAsyncRendering;this.j.enableAsyncRendering=function(){a.G||(a.ca.hb=!0);h.apply(this,arguments)}};u.prototype.Ga=function(a){return a.hasOwnProperty("isOutOfPage")&&a.isOutOfPage};z.prototype.v=function(a){this.h=a};z.prototype.l=function(a){var b={};a=V(a);for(var c=a.next();!c.done;c=a.next()){var c=
this.b.h(c.value),d=null,g;for(g in this.a)if(this.a[g].u==c){d=this.a[g].id;break}null!=d&&(b[d]=this.a[d])}return b};z.prototype.f=function(a){var b=this,c={},d={};a.forEach(function(a){var g=b.b.h(a),e=b.b.R(a);if(!(g in d)){c[e]=c[e]++||1;var f=B();d[f]={m:e,dc:e+":"+c[e],u:g,id:f,cc:!1,Xb:!1,aa:!1,wb:{},ta:[],Oa:{},sizes:b.b.v(a),La:{},Vb:b.b.Ga(a),ka:b.b.v.bind(b.b,a),za:!1,xa:!1,Fb:0}}});this.a=Object.assign(this.a,d)};z.prototype.Ab=function(a){for(var b in a)if(b in this.a){var c=this.a[b].u;
this.a[b].Oa=a[b];this.a[b].La=a[b].targeting;var d=Object.assign({},this.i.ta)[a[b].id];d&&(d.fa=a[b].creative,d.size=a[b].size,d.La=a[b].targeting,this.a[b].La.sbi_size=a[b].size,this.b.Na(c,a[b].targeting))}};w.Object.defineProperties(z.prototype,{C:{configurable:!0,enumerable:!0,get:function(){return this.a},set:function(a){this.a=a}}});J.prototype.ja=function(a){return a?this.a[a]:this.a};O.prototype.$=function(a,b){if(a){a=this.a[a];if(b){var c=a[b];r.Ea(b)&&!c?a=this.P.ja(b):a=c}return a}return this.a};
F.prototype.Va=function(a){var b=a.key;a=this.b[void 0===a.B?this.B:a.B];if(b){var c=a[b];r.Ea(b)&&!c?a=this.H.$(r.ia(this.H.$()),b):a=c}return a};F.prototype.Wa=function(a){var b=a.name;return this.i({B:void 0===a.B?this.B:a.B,na:void 0===a.na?"requestSettings":a.na}).find(function(a){return a.name===b})};F.prototype.i=function(a){var b=[];a=this.b[void 0===a.B?this.B:a.B][void 0===a.na?"requestSettings":a.na]||[];for(var c=0;c<a.length;c++){var d=a[c];if(d.hasOwnProperty("dimensions")){var g="*";
this.H.a&&(g=r.ia(this.H.$()));Z(d)&&Y(d,g)&&b.push(d)}else b.push(d)}return b};w.Object.defineProperties(F.prototype,{h:{configurable:!0,enumerable:!0,get:function(){var a="*";this.H.a&&(a=r.ia(this.H.$()));var b=1;"number"===typeof this.a.frequency&&(b=this.a.frequency);return!this.a.disabled&&this.v(this.a,a,"platforms")&&this.l(this.a,"domain")&&Math.random()<=b}}});X.prototype.start=function(a,b,c){this.a||(this.c=c,a.Va({}),this.qa=a,this.a=!0,c.log("sbi",200011,[this.name]),this.b=this.Ka(a,
b,c)||Promise.resolve({}));return this.b};I.prototype.clone=function(){return Object.assign(Object.create(this),this)};I.prototype.ha=function(a){var b=this.clone();switch(a){case 1:a={buyerid:b.T,buyername:b.ea,adunit_code:b.S,pageViewId:b.W,bidid:b.da,p:1,response:b.Y,s:b.Z||"0x0",bid:b.X,latency:b.la,jsLatency:b.V};break;case 2:a={buyerid:b.T,buyername:b.ea,adunit_code:b.S,pageViewId:b.W,bidid:b.da,p:2,response:b.Y,s:b.Z||"0x0",bid:b.X,latency:b.la,jsLatency:b.V};b.J&&"string"==typeof b.J&&(a.dealid=
b.pa);break;default:a={buyerid:b.T,buyername:b.ea,adunit_code:b.S,pageViewId:b.W,bidid:b.da,p:3,response:b.Y,s:b.Z||"0x0",bid:b.X,latency:b.la,jsLatency:b.V}}return a};w.Object.defineProperties(I.prototype,{id:{configurable:!0,enumerable:!0,get:function(){return this.da}},ub:{configurable:!0,enumerable:!0,get:function(){return this.W},set:function(a){this.W=a}},m:{configurable:!0,enumerable:!0,get:function(){return this.l},set:function(a){this.l=a}},type:{configurable:!0,enumerable:!0,get:function(){return this.v},
set:function(a){this.v=a}},bb:{configurable:!0,enumerable:!0,get:function(){return this.S},set:function(a){this.S=a}},g:{configurable:!0,enumerable:!0,get:function(){return this.X},set:function(a){this.X=a}},A:{configurable:!0,enumerable:!0,get:function(){return this.ea}},Ya:{configurable:!0,enumerable:!0,get:function(){return this.i},set:function(a){this.i=a}},R:{configurable:!0,enumerable:!0,get:function(){return 0>=this.a||!this.a?-1:this.a},set:function(a){this.a=Math.round(a)}},la:{configurable:!0,
enumerable:!0,get:function(){return 0>=this.a||!this.a?-1:Math.round(this.a)},set:function(a){this.a=Math.round(a)}},nb:{configurable:!0,enumerable:!0,get:function(){return Math.round(this.V)},set:function(a){this.V=Math.round(a)}},size:{configurable:!0,enumerable:!0,get:function(){return this.Z},set:function(a){this.Z=Array.isArray(a)?a.join("x"):a}},ua:{configurable:!0,enumerable:!0,get:function(){return this.T},set:function(a){this.T=a}},fa:{configurable:!0,enumerable:!0,get:function(){return this.b},
set:function(a){this.b=a}},J:{configurable:!0,enumerable:!0,get:function(){return this.pa},set:function(a){this.pa=a}},N:{configurable:!0,enumerable:!0,get:function(){return this.f},set:function(a){this.f=a}},response:{configurable:!0,enumerable:!0,get:function(){return this.Y},set:function(a){this.Y=a}},ya:{configurable:!0,enumerable:!0,get:function(){return this.h},set:function(a){this.h=a}}});var ja={sonobi:new X({Ka:function(a,b,c){this.qa=a;this.L=b;this.c=c;this.c.log("sbi",200022,["sonobi"])},
request:function(a,b,c,d){var g=this,e=this;c={};var f={},h;for(h in a){var k=a[h],l=k.m+"|"+encodeURIComponent(k.u);c[l]=k.sizes.join(",");f[l]=new I(k.sizes[0],"sonobi","sonobi",h,k.m,this.L,b)}b=JSON.stringify(c);h=C(this.qa);c=location.protocol+"//apex.go.sonobi.com/trinity.js?key_maker=";var m=r.Ba();b=c+b+"&cv=%%callback%%"+h+("&s="+m);e.c.log("sbi",200023,["sonobi",a]);return this.caller.ob(b).then(function(b){e.c.log("sbi",200024,["sonobi",a,b]);var c=b.visibility||[],h=r.jb(m);c.forEach(function(a){return g.caller.Ta(a)});
b=e.parse.call(e,b,a,h,f);d.ra(b);return b})},parse:function(a,b,c,d){var e={},f;for(f in b){var h=b[f],k=h.m+"|"+h.u,l=h.m+"|"+encodeURIComponent(h.u);k in a.slots&&(l=d[l],k=a.slots[k],"sbi_aid"in k||(k={sbi_aid:null,sbi_apoc:null,sbi_size:null}),"sbi_dozer"in k||(k.sbi_dozer=!1),"sbi_pri"in k||(k.sbi_pri=10),"sbi_mouse"in k||(k.sbi_mouse=0,k.sbi_pri=1),l.g=100*parseFloat(k.sbi_mouse),l.size=k.sbi_size||l.size,l.J=k.sbi_dozer,l.type=k.sbi_ct||l.type,l.N=parseInt(k.sbi_pri,10),l.la=c,l.Ya={sbi_aid:k.sbi_aid,
sbi_dc:a.sbi_dc},l.fa=r.fb("//%%sbi_dc%%apex.go.sonobi.com/sbi.js?aid=%%sbi_aid%%&as=null","SCRIPT"),l.bb=h.m,k.sbi_dozer&&(l.ya={sbi_dozer:k.sbi_dozer}),e[h.id]=[l])}this.c.log("sbi",200025,["sonobi",b,e]);return e},name:"sonobi",ua:"sonobi",Yb:C,Ob:t,Nb:x})};f.prototype.f=function(a,b,c){var d=this,e=this.a[b].o;this.a[b].o[c].D||this.a[b].D?(Object.assign(this.a[b].o[c].vb,a),"function"===typeof this.L.O&&Object.keys(a).forEach(function(b){a[b].forEach(function(a){a.response=2;d.L.O(a.ha(2))})}),
this.a[b].o[c].D&&this.c.log("sbi",200037,[a]),this.a[b].D&&this.c.log("sbi",200038,[a])):(Object.assign(this.a[b].o[c].ab,a),e[c].$a=0,clearTimeout(this.a[b].o[c].Ia),0>=Object.keys(e).reduce(function(a,b){return a+=e[b].$a},0)&&(clearTimeout(this.a[b].Ia),this.h(b)))};f.prototype.h=function(a){var b=this.a[a].o,c=Object.keys(b).reduce(function(a,c){var d=b[c].ab;Object.keys(d).forEach(function(b){d[b].forEach(function(b){a[b.id]=b})});return a},{});this.b=Object.assign(this.b,c);this.a[a].done(c)};
f.prototype.yb=function(a,b,c,d,e){var f=this;this.c.log("sbi",200001,[c]);this.c.log("sbi",200006);this.a[d]={done:e,D:!1,o:{},Ia:setTimeout(function(){f.c.log("sbi",200009);f.a[d].D=!0;Object.keys(f.a[d].o).forEach(function(a){f.a[d].o[a].D=!0});f.h(d)},c)};aa(b.adapterSettings).forEach(function(c){var e=c.name,g=new F(b,e);if(g.h){c=c.sizes;f.c.log("sbi",200011,[e]);var h={},l;for(l in a)if(a.hasOwnProperty(l)){a[l].sizes=a[l].ka();var m=ea(a[l].sizes,c);0<m.length&&(h[l]=Object.assign({},a[l]),
h[l].sizes=m)}if(0<Object.keys(h).length){var q=k.performance.now(),n=g.Va({key:"timeout"});f.a[d].o[e]={ab:{},vb:{},ub:d,D:!1,$a:1,ra:function(a){var b=Math.round(k.performance.now()-q);Object.keys(a).forEach(function(c){a[c].forEach(function(a){a.ba=!1;a.nb=b})});f.f(a,d,e)},Ia:setTimeout(function(){f.c.log("sbi",200008,[e,n]);f.f([],d,e);f.a[d].o[e].D=!0},n)};ja[e].start(g,f.L,f.c).then(function(a){ja[e].request(h,d,a,f.a[d].o[e])})}}})};f.prototype.kb=function(a,b){if(0==a.length)return{};var c=
{};a.forEach(function(a){c[a.m]=c[a.m]||[];c[a.m]=c[a.m].concat(a)});a={};for(var d in c){var e=ia.sonobiDealWinsOverHighestCPM(c[d],this.c);if(null!=e){e.Pa=!0;a[d]={targeting:{}};a[d].id=e.id;a[d].targeting.sbi_kmid=e.id;a[d].targeting.sbi_bidder=e.A;a[d].targeting.sbi_ct=e.type;var f=ga(e.g,b);"number"===typeof f&&0<f&&(a[d].targeting.sbi_price=f);for(var h in e.ya)a[d].targeting[h]=e.ya[h];f=e.fa;f=ha(f,e.Ya,"%%");a[d].creative=f;a[d].size=e.size}}this.c.log("sbi",200005,[a]);return a};w.Object.defineProperties(f.prototype,
{ta:{configurable:!0,enumerable:!0,get:function(){return this.b},set:function(a){this.b=a}}});m.prototype.O=function(a){var b=this;this.a.length||setTimeout(function(){b.i(b.a);b.a=[]},100);this.a.push(a)};m.prototype.h=function(a,b){var c=0;a.eb&&(c|=16);a.D&&(c|=8);a.Pa&&(c|=4);a.ba&&(c|=2);a.Da&&(c|=1);switch(c){case 0:return 1;case 8:return 0;case 16:return 4;case 17:return 4;case 20:case 21:return this.c.log("sbi",200018,[b.g,b.A]),5;case 22:case 23:return 6;case 24:return 2;case 25:return this.c.log("sbi",
200016),3;default:throw Error("Invalid bid status: "+c.toString(2)||"Assertion failed!");}};m.prototype.f=function(a){var b={g:0};a=V(a);for(var c=a.next();!c.done;c=a.next())c=c.value,c.g>b.g&&(b=c);b.Da=!0};m.prototype.ra=function(a){this.f(a);a=V(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;this.c.log("sbi",200026,[b.A,b]);var c={eb:0<b.g||b.J,D:b.Tb||b.Gb,Pa:b.Pa,ba:b.ba,Da:b.Da},d=void 0;try{d=this.h(c,b),b.response=d}catch(g){this.c.log(200020,[g.message])}this.O(b.ha(2))}};m.prototype.i=
function(a){var b=void 0,c=void 0,b=void 0===b?this.b.cb.ib():b,c=void 0===c?r.Ba():c,d=this,e=r.mb(a,"pageViewId");Object.keys(e).forEach(function(a){var c=e[a].map(function(a){return r.qb(a,["pageViewId"])});a=b+"?pageviewid="+a+"&corscred=1&ver="+k.sbi_km.version;c=JSON.stringify(c);return d.caller.b(a,c)})};n.prototype.ib=function(){var a=this.a.url;r.Ea("url")&&!a&&(a=this.P.ja("url"));return a};if(!k.hasOwnProperty("sbi_km")||!k.sbi_km.apiReady){r.zb(500);var T=new l(h),y=new H(h),U=new m(y,
T),ka=new f(y,U),Aa=k.sbi_morpheus=e(),la=k.sbi_km=k.sbi_km||{API:{debug:y.h.bind(y),getLog:y.b.bind(y)},config:h,apiReady:!1};k.addEventListener("message",function(a){"SAFE_FRAME_RENDER"===a.data.key&&a.source&&k.sbi_km.API.render(a.source,a.data.id,a.data.macros,!0)},!1);y=new z(y,h,ka,U);y.v(xa(ka,h,T.P.ja("timeout"),y,T,U).xb);-1===k.location.search.indexOf("sbi_test")?document.cookie="sbi_debug=false":-1!==document.cookie.indexOf("sbi_debug=true")?la.API.debug(!0):-1!==k.location.search.indexOf("sbi_test")&&
(document.cookie="sbi_debug=true",la.API.debug(!0));Aa.initialize();k.sbi_km.apiReady=!0}}).call(this,window.sbi_config||{adServer:"dfp",url:"//mtrx.go.sonobi.com",analyticsSettings:{url:"https://keymaker.go.sonobi.com/keymaker",timeout:2E3},globalSettings:{sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),priceRules:[{set:3E3,ge:3E3},{round:5,ge:900,lt:3E3},{round:1,lt:900}],timeout:1600},platformSettings:{mobile:{viewport:{lt:768}},
tablet:{viewport:{lt:992,ge:768}},desktop:{viewport:{ge:992}}},adapterSettings:[{name:"sonobi",disabled:!1,timeout:1500,sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),platforms:["mobile","desktop","tablet"],requestSettings:[{name:"cdf",value:"guardian.ophan.pageViewId",dimensions:{sizes:[],adUnits:[],platforms:[],domains:[]}},{dimensions:{adUnits:[],domains:[],platforms:[],sizes:[]},name:"ant",value:"guardian.config.page.appNexusPageTargeting"}],
priceRules:[],parseSettings:[]}]});window.sbi_km.version="3.7.10";}).call(window)
